# https://github.com/nodejs/docker-node#create-a-dockerfile-in-your-nodejs-app-project
version: "2"
services:  
    blockchain_tests:
      image: "node:14.3.0-slim"
      user: "node"
      working_dir: /home/joj/src
      environment:
        - NODE_ENV=dev
        - NPM_CONFIG_LOGLEVEL=error
      volumes:
        - ./src:/home/joj/src
      command: bash -c  "npm --prefix /home/joj/src/blockchain install --silent --progress=false ; npm --prefix /home/joj/src/blockchain run test-all"
      networks:
        - tjoj-network
    
    chapter_listings:
      image: "node:14.3.0-slim"
      user: "node"
      working_dir: /home/joj/src
      environment:
        - NODE_ENV=dev
        - NPM_CONFIG_LOGLEVEL=error
      volumes:
        - ./src:/home/joj/src
      command: bash -c  "npm --prefix /home/joj/src/blockchain install; npm --prefix /home/joj/src/blockchain run build ; npm --prefix /home/joj/src/chapter-listings install --silent --progress=false ; npm --prefix /home/joj/src/chapter-listings run test-all"
      networks:
      - tjoj-network
networks:
  tjoj-network: